---
# tasks file for podman-nginx

- name: Ensure configuration directory is present
  file:
    state: directory
    path: "{{ nginx_conf_dir }}/conf.d"
    owner: "root"
    group: "root"
    mode: 0755
  tags: ['nginx']

- name: Ensure vhosts directory is present
  file:
    state: directory
    path: "{{ nginx_conf_dir }}/vhosts.d"
    owner: "root"
    group: "root"
    mode: 0755
  tags: ['nginx']

- name: Ensure logs directory is present
  file:
    state: directory
    path: "{{nginx_log_directory}}"
    owner: "root"
    group: "root"
    mode: 0755
  tags: ['nginx']
  when: nginx_log_directory != ""

- name: Ensure configuration templates are present
  copy:
    src: nginx/
    dest: "{{ nginx_conf_dir }}/"
    owner: root
    group: root
    mode: 0644
  notify: restart nginx
  tags: ['nginx']

- name: Ensure configuration file is present
  template:
    src: config.j2
    dest: "{{ nginx_conf_dir }}/nginx.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart nginx
  tags: ['nginx']

- name: Ensure default.conf file is present
  template:
    src: default.j2
    dest: "{{ nginx_conf_dir }}/vhosts.d/default.conf"
    owner: root
    group: root
    mode: 0644
    force: false
  notify: restart nginx
  when: nginx_default_conf
  tags: ['nginx']

- name: Ensure www directory is present
  file:
    state: directory
    path: "{{ nginx_data_dir }}/htdocs"
    owner: "root"
    group: "root"
    mode: 0755
  tags: ['nginx']

- name: Ensure index.html is present
  copy:
    src: index.html
    dest: "{{ nginx_data_dir }}/htdocs/index.html"
    owner: "root"
    group: "root"
    mode: 0644
  tags: ['nginx']

- name: Ensure systemd file is up-to-date
  template:
    src: systemd/nginx_service.j2
    dest: "/etc/systemd/system/{{nginx_service_name}}.service"
    owner: root
    group: root
    mode: 0644
    force: true
  register: nginx_service_install
  notify: restart nginx
  tags: ['nginx']

- name: Reload systemd
  systemd:
    daemon_reload: true
  when: nginx_service_install.changed
  tags: ['nginx']

- name: Ensure nginx is enabled
  systemd:
    name: "{{nginx_service_name}}"
    state: started
    enabled: yes
  tags: ['nginx']
